// Generated by gencpp from file projectx/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_ADDTWOINTS_H
#define PROJECTX_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <projectx/AddTwoIntsRequest.h>
#include <projectx/AddTwoIntsResponse.h>


namespace projectx
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace projectx


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::projectx::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::projectx::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::projectx::AddTwoInts > {
  static const char* value()
  {
    return "projectx/AddTwoInts";
  }

  static const char* value(const ::projectx::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::projectx::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::projectx::AddTwoInts > 
template<>
struct MD5Sum< ::projectx::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::projectx::AddTwoInts >::value();
  }
  static const char* value(const ::projectx::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::projectx::AddTwoIntsRequest> should match 
// service_traits::DataType< ::projectx::AddTwoInts > 
template<>
struct DataType< ::projectx::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::projectx::AddTwoInts >::value();
  }
  static const char* value(const ::projectx::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::projectx::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::projectx::AddTwoInts > 
template<>
struct MD5Sum< ::projectx::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::projectx::AddTwoInts >::value();
  }
  static const char* value(const ::projectx::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::projectx::AddTwoIntsResponse> should match 
// service_traits::DataType< ::projectx::AddTwoInts > 
template<>
struct DataType< ::projectx::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::projectx::AddTwoInts >::value();
  }
  static const char* value(const ::projectx::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECTX_MESSAGE_ADDTWOINTS_H
