// Generated by gencpp from file projectx/MotorOutSingleArray.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_MOTOROUTSINGLEARRAY_H
#define PROJECTX_MESSAGE_MOTOROUTSINGLEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace projectx
{
template <class ContainerAllocator>
struct MotorOutSingleArray_
{
  typedef MotorOutSingleArray_<ContainerAllocator> Type;

  MotorOutSingleArray_()
    : id()
    , pos()  {
      id.assign(0);

      pos.assign(0);
  }
  MotorOutSingleArray_(const ContainerAllocator& _alloc)
    : id()
    , pos()  {
      id.assign(0);

      pos.assign(0);
  }



   typedef boost::array<int64_t, 21>  _id_type;
  _id_type id;

   typedef boost::array<int64_t, 21>  _pos_type;
  _pos_type pos;




  typedef boost::shared_ptr< ::projectx::MotorOutSingleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projectx::MotorOutSingleArray_<ContainerAllocator> const> ConstPtr;

}; // struct MotorOutSingleArray_

typedef ::projectx::MotorOutSingleArray_<std::allocator<void> > MotorOutSingleArray;

typedef boost::shared_ptr< ::projectx::MotorOutSingleArray > MotorOutSingleArrayPtr;
typedef boost::shared_ptr< ::projectx::MotorOutSingleArray const> MotorOutSingleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projectx::MotorOutSingleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projectx::MotorOutSingleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace projectx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'projectx': ['/home/rock/ProjectX/ROS/src/projectx/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projectx::MotorOutSingleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::MotorOutSingleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::MotorOutSingleArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de04d0ab49b6de06afa1f92fbae073c5";
  }

  static const char* value(const ::projectx::MotorOutSingleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde04d0ab49b6de06ULL;
  static const uint64_t static_value2 = 0xafa1f92fbae073c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projectx/MotorOutSingleArray";
  }

  static const char* value(const ::projectx::MotorOutSingleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[21] id\n\
int64[21] pos\n\
";
  }

  static const char* value(const ::projectx::MotorOutSingleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorOutSingleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projectx::MotorOutSingleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projectx::MotorOutSingleArray_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECTX_MESSAGE_MOTOROUTSINGLEARRAY_H
