// Generated by gencpp from file projectx/MotorBoost.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_MOTORBOOST_H
#define PROJECTX_MESSAGE_MOTORBOOST_H

#include <ros/service_traits.h>


#include <projectx/MotorBoostRequest.h>
#include <projectx/MotorBoostResponse.h>


namespace projectx
{

struct MotorBoost
{

typedef MotorBoostRequest Request;
typedef MotorBoostResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorBoost
} // namespace projectx


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::projectx::MotorBoost > {
  static const char* value()
  {
    return "22188d050a80d588351715cedf3044c4";
  }

  static const char* value(const ::projectx::MotorBoost&) { return value(); }
};

template<>
struct DataType< ::projectx::MotorBoost > {
  static const char* value()
  {
    return "projectx/MotorBoost";
  }

  static const char* value(const ::projectx::MotorBoost&) { return value(); }
};


// service_traits::MD5Sum< ::projectx::MotorBoostRequest> should match 
// service_traits::MD5Sum< ::projectx::MotorBoost > 
template<>
struct MD5Sum< ::projectx::MotorBoostRequest>
{
  static const char* value()
  {
    return MD5Sum< ::projectx::MotorBoost >::value();
  }
  static const char* value(const ::projectx::MotorBoostRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::projectx::MotorBoostRequest> should match 
// service_traits::DataType< ::projectx::MotorBoost > 
template<>
struct DataType< ::projectx::MotorBoostRequest>
{
  static const char* value()
  {
    return DataType< ::projectx::MotorBoost >::value();
  }
  static const char* value(const ::projectx::MotorBoostRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::projectx::MotorBoostResponse> should match 
// service_traits::MD5Sum< ::projectx::MotorBoost > 
template<>
struct MD5Sum< ::projectx::MotorBoostResponse>
{
  static const char* value()
  {
    return MD5Sum< ::projectx::MotorBoost >::value();
  }
  static const char* value(const ::projectx::MotorBoostResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::projectx::MotorBoostResponse> should match 
// service_traits::DataType< ::projectx::MotorBoost > 
template<>
struct DataType< ::projectx::MotorBoostResponse>
{
  static const char* value()
  {
    return DataType< ::projectx::MotorBoost >::value();
  }
  static const char* value(const ::projectx::MotorBoostResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECTX_MESSAGE_MOTORBOOST_H
