// Generated by gencpp from file projectx/Tabpage.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_TABPAGE_H
#define PROJECTX_MESSAGE_TABPAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace projectx
{
template <class ContainerAllocator>
struct Tabpage_
{
  typedef Tabpage_<ContainerAllocator> Type;

  Tabpage_()
    : header()
    , tabpage()  {
    }
  Tabpage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tabpage(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tabpage_type;
  _tabpage_type tabpage;




  typedef boost::shared_ptr< ::projectx::Tabpage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projectx::Tabpage_<ContainerAllocator> const> ConstPtr;

}; // struct Tabpage_

typedef ::projectx::Tabpage_<std::allocator<void> > Tabpage;

typedef boost::shared_ptr< ::projectx::Tabpage > TabpagePtr;
typedef boost::shared_ptr< ::projectx::Tabpage const> TabpageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projectx::Tabpage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projectx::Tabpage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace projectx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
<<<<<<< HEAD
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'projectx': ['/home/ubuntu/ProjectX/ROS/src/projectx/msg']}
=======
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'projectx': ['/home/kaaninan/ProjectX/ROS/src/projectx/msg']}
>>>>>>> develop

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::projectx::Tabpage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projectx::Tabpage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::Tabpage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::Tabpage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::Tabpage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::Tabpage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projectx::Tabpage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4213ffb5a43e14111c66fe04a2d8f4ec";
  }

  static const char* value(const ::projectx::Tabpage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4213ffb5a43e1411ULL;
  static const uint64_t static_value2 = 0x1c66fe04a2d8f4ecULL;
};

template<class ContainerAllocator>
struct DataType< ::projectx::Tabpage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projectx/Tabpage";
  }

  static const char* value(const ::projectx::Tabpage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projectx::Tabpage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Used for tabpage switching\n\
\n\
Header header\n\
string tabpage\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::projectx::Tabpage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projectx::Tabpage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tabpage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Tabpage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projectx::Tabpage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projectx::Tabpage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tabpage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tabpage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECTX_MESSAGE_TABPAGE_H
