// Generated by gencpp from file projectx/XYPad.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_XYPAD_H
#define PROJECTX_MESSAGE_XYPAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <projectx/CommonProperties.h>

namespace projectx
{
template <class ContainerAllocator>
struct XYPad_
{
  typedef XYPad_<ContainerAllocator> Type;

  XYPad_()
    : header()
    , common()
    , range()
    , x(0.0)
    , y(0.0)
    , z(false)  {
      range.assign(0.0);
  }
  XYPad_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , common(_alloc)
    , range()
    , x(0.0)
    , y(0.0)
    , z(false)  {
      range.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::projectx::CommonProperties_<ContainerAllocator>  _common_type;
  _common_type common;

   typedef boost::array<float, 2>  _range_type;
  _range_type range;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::projectx::XYPad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projectx::XYPad_<ContainerAllocator> const> ConstPtr;

}; // struct XYPad_

typedef ::projectx::XYPad_<std::allocator<void> > XYPad;

typedef boost::shared_ptr< ::projectx::XYPad > XYPadPtr;
typedef boost::shared_ptr< ::projectx::XYPad const> XYPadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projectx::XYPad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projectx::XYPad_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace projectx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'projectx': ['/home/rock/ProjectX/ROS/src/projectx/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::projectx::XYPad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projectx::XYPad_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::XYPad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::XYPad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::XYPad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::XYPad_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projectx::XYPad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee31b4143f668690ed4f5b021cf85341";
  }

  static const char* value(const ::projectx::XYPad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee31b4143f668690ULL;
  static const uint64_t static_value2 = 0xed4f5b021cf85341ULL;
};

template<class ContainerAllocator>
struct DataType< ::projectx::XYPad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projectx/XYPad";
  }

  static const char* value(const ::projectx::XYPad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projectx::XYPad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TouchOSC XYPad Control\n\
\n\
Header header\n\
CommonProperties common\n\
float32[2] range\n\
float32 x\n\
float32 y\n\
bool z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: projectx/CommonProperties\n\
# Common functionality to all TouchOSC controls\n\
\n\
string tabpage          # Control tabpage\n\
string name             # Control Name\n\
int16 x                 # X position of the control\n\
int16 y                 # Y position of the control\n\
uint16 width            # Width of the control\n\
uint16 height           # Height of the control\n\
string visible          # Visibility of the control\n\
\n\
# Possible colors are:\n\
# \"red\", \"green\", \"blue\", \"yellow\", \"orange\", \"purple\", \"gray\"\n\
string color            # Color of the control\n\
";
  }

  static const char* value(const ::projectx::XYPad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projectx::XYPad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.common);
      stream.next(m.range);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct XYPad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projectx::XYPad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projectx::XYPad_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "common: ";
    s << std::endl;
    Printer< ::projectx::CommonProperties_<ContainerAllocator> >::stream(s, indent + "  ", v.common);
    s << indent << "range[]" << std::endl;
    for (size_t i = 0; i < v.range.size(); ++i)
    {
      s << indent << "  range[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.range[i]);
    }
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECTX_MESSAGE_XYPAD_H
