(cl:defpackage projectx-srv
  (:use )
  (:export
   "MOTORBOOST"
   "<MOTORBOOST-REQUEST>"
   "MOTORBOOST-REQUEST"
   "<MOTORBOOST-RESPONSE>"
   "MOTORBOOST-RESPONSE"
   "SENSORTEMP"
   "<SENSORTEMP-REQUEST>"
   "SENSORTEMP-REQUEST"
   "<SENSORTEMP-RESPONSE>"
   "SENSORTEMP-RESPONSE"
   "SPEECH"
   "<SPEECH-REQUEST>"
   "SPEECH-REQUEST"
   "<SPEECH-RESPONSE>"
   "SPEECH-RESPONSE"
  ))

