// Generated by gencpp from file projectx/MotorIn.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_MOTORIN_H
#define PROJECTX_MESSAGE_MOTORIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace projectx
{
template <class ContainerAllocator>
struct MotorIn_
{
  typedef MotorIn_<ContainerAllocator> Type;

  MotorIn_()
    : id(0)
    , temp(0)
    , voltage(0)
    , pos(0)  {
    }
  MotorIn_(const ContainerAllocator& _alloc)
    : id(0)
    , temp(0)
    , voltage(0)
    , pos(0)  {
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef int64_t _temp_type;
  _temp_type temp;

   typedef int64_t _voltage_type;
  _voltage_type voltage;

   typedef int64_t _pos_type;
  _pos_type pos;




  typedef boost::shared_ptr< ::projectx::MotorIn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projectx::MotorIn_<ContainerAllocator> const> ConstPtr;

}; // struct MotorIn_

typedef ::projectx::MotorIn_<std::allocator<void> > MotorIn;

typedef boost::shared_ptr< ::projectx::MotorIn > MotorInPtr;
typedef boost::shared_ptr< ::projectx::MotorIn const> MotorInConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projectx::MotorIn_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projectx::MotorIn_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace projectx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'projectx': ['/home/kaaninan/ProjectX/ROS/src/projectx/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::projectx::MotorIn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projectx::MotorIn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::MotorIn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::MotorIn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::MotorIn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::MotorIn_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projectx::MotorIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59d687bf83d746923bba32a479b2cd0d";
  }

  static const char* value(const ::projectx::MotorIn_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59d687bf83d74692ULL;
  static const uint64_t static_value2 = 0x3bba32a479b2cd0dULL;
};

template<class ContainerAllocator>
struct DataType< ::projectx::MotorIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projectx/MotorIn";
  }

  static const char* value(const ::projectx::MotorIn_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projectx::MotorIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n\
int64 temp\n\
int64 voltage\n\
int64 pos\n\
";
  }

  static const char* value(const ::projectx::MotorIn_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projectx::MotorIn_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.temp);
      stream.next(m.voltage);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorIn_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projectx::MotorIn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projectx::MotorIn_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "temp: ";
    Printer<int64_t>::stream(s, indent + "  ", v.temp);
    s << indent << "voltage: ";
    Printer<int64_t>::stream(s, indent + "  ", v.voltage);
    s << indent << "pos: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECTX_MESSAGE_MOTORIN_H
