// Generated by gencpp from file projectx/TouchOSC_Common.msg
// DO NOT EDIT!


#ifndef PROJECTX_MESSAGE_TOUCHOSC_COMMON_H
#define PROJECTX_MESSAGE_TOUCHOSC_COMMON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <projectx/CommonProperties.h>

namespace projectx
{
template <class ContainerAllocator>
struct TouchOSC_Common_
{
  typedef TouchOSC_Common_<ContainerAllocator> Type;

  TouchOSC_Common_()
    : header()
    , common()  {
    }
  TouchOSC_Common_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , common(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::projectx::CommonProperties_<ContainerAllocator>  _common_type;
  _common_type common;




  typedef boost::shared_ptr< ::projectx::TouchOSC_Common_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projectx::TouchOSC_Common_<ContainerAllocator> const> ConstPtr;

}; // struct TouchOSC_Common_

typedef ::projectx::TouchOSC_Common_<std::allocator<void> > TouchOSC_Common;

typedef boost::shared_ptr< ::projectx::TouchOSC_Common > TouchOSC_CommonPtr;
typedef boost::shared_ptr< ::projectx::TouchOSC_Common const> TouchOSC_CommonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projectx::TouchOSC_Common_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projectx::TouchOSC_Common_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace projectx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'projectx': ['/home/kaaninan/ProjectX/ROS/src/projectx/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::projectx::TouchOSC_Common_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projectx::TouchOSC_Common_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::TouchOSC_Common_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projectx::TouchOSC_Common_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::TouchOSC_Common_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projectx::TouchOSC_Common_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projectx::TouchOSC_Common_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02b274e5694f91306b366760eaca24ef";
  }

  static const char* value(const ::projectx::TouchOSC_Common_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02b274e5694f9130ULL;
  static const uint64_t static_value2 = 0x6b366760eaca24efULL;
};

template<class ContainerAllocator>
struct DataType< ::projectx::TouchOSC_Common_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projectx/TouchOSC_Common";
  }

  static const char* value(const ::projectx::TouchOSC_Common_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projectx::TouchOSC_Common_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TouchOSC Common Control\n\
# Battery, Time\n\
\n\
Header header\n\
CommonProperties common\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: projectx/CommonProperties\n\
# Common functionality to all TouchOSC controls\n\
\n\
string tabpage          # Control tabpage\n\
string name             # Control Name\n\
int16 x                 # X position of the control\n\
int16 y                 # Y position of the control\n\
uint16 width            # Width of the control\n\
uint16 height           # Height of the control\n\
string visible          # Visibility of the control\n\
\n\
# Possible colors are:\n\
# \"red\", \"green\", \"blue\", \"yellow\", \"orange\", \"purple\", \"gray\"\n\
string color            # Color of the control\n\
";
  }

  static const char* value(const ::projectx::TouchOSC_Common_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projectx::TouchOSC_Common_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.common);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TouchOSC_Common_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projectx::TouchOSC_Common_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projectx::TouchOSC_Common_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "common: ";
    s << std::endl;
    Printer< ::projectx::CommonProperties_<ContainerAllocator> >::stream(s, indent + "  ", v.common);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECTX_MESSAGE_TOUCHOSC_COMMON_H
