(cl:defpackage projectx-srv
  (:use )
  (:export
   "PIN"
   "<PIN-REQUEST>"
   "PIN-REQUEST"
   "<PIN-RESPONSE>"
   "PIN-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SENSORTEMP"
   "<SENSORTEMP-REQUEST>"
   "SENSORTEMP-REQUEST"
   "<SENSORTEMP-RESPONSE>"
   "SENSORTEMP-RESPONSE"
  ))

